# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flutt',
            old_name='flutt_text',
            new_name='comment',
        ),
    ]
