# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0002_auto_20160519_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutt',
            name='comment',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='flutt',
            name='user_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=32),
        ),
    ]
