# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0003_auto_20160519_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutt',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=32),
        ),
    ]
