# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0007_auto_20160519_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flutt',
            options={'ordering': ('-datetime',)},
        ),
    ]
